### ISSUE TITLE
A brief report about neurotic

### ISSUE THREAD

**Issue by jpgill86** [jpgill86/neurotic#152]
Hi @samuelgarcia!

The journal eNeuro [announced](https://www.eneuro.org/content/6/5/ENEURO.0342-19.2019) a new category of paper about open source tools and methods, and I have begun working on a brief report about neurotic that I think fits the bill. If things go well, I'd like to submit within the next couple weeks. It would be nice to get some additional exposure for neurotic, ephyviewer, and Neo!

Since neurotic is built on top of so much of your stuff, particularly ephyviewer, I want to extend a coauthorship invitation to you to acknowledge all your hard work which was instrumental to getting my app working. You don't have to decide now. I'm still in the early stages of assembling the manuscript, so you can wait to see my writing, decide it's terrible, and decline then. 😋 I will certainly cite your Neo paper, regardless!

I'm not asking for anything in exchange, though I am interested in finding more small, diverse data sets that I could use as examples of what neurotic can do. For example, I'm in contact with another group that has human EMG muscle data with accompanying video, which I think could be an interesting demonstration of neurotic's (and ephyviewer's !) features. If you have been involved in any projects with data that works well with ephyviewer, and for which acquiring permission to use it to promote neurotic would be uncomplicated (possibly already published and open access), I'd love to discuss it!

**Comment by jpgill86** [comment]
The paper was published here earlier this year:
> Gill, J. P., Garcia, S., Ting, L. H., Wu, M., & Chiel, H. J. (2020).
*neurotic*: Neuroscience Tool for Interactive Characterization. eNeuro,
7(3). https://doi.org/10.1523/ENEURO.0085-20.2020

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
Maybe you could mention this paper in the doc of ephyviewer too or in the readme. no ?

**Comment by jpgill86** [comment]
> Hi Jeffrey.
> Maybe you could mention this paper in the doc of ephyviewer too or in the readme. no ?

Good idea! I'll do that.
