### ISSUE TITLE
Add neurotic to NeuralEnsemble.org?

### ISSUE THREAD

**Issue by jpgill86** [jpgill86/neurotic#159]
Hi @apdavison,

Earlier this year on the NeuralEnsemble mailing list, I [announced](https://groups.google.com/d/msg/neuralensemble/8Fhbn-VXVS4/rdnwGlPCAgAJ) the release of my app, called neurotic, which makes use of Neo and other Neo-ecosystem libraries. @samuelgarcia suggested that I ask you about the possibility of adding neurotic to [NeuralEnsemble.org](http://neuralensemble.org/)'s listings of software projects. I am wondering if you would be amenable to this idea, and how we would go about doing that (or if there is someone else I should bother with this!).

Thanks for your time!

**Comment by apdavison** [comment]
Hi @jpgill86 - yes, I think that makes a lot of sense. I guess I can get most of the information needed (licence, documentation URL, etc.) from Github, but I will need a short description (1-2 sentences), and then a longer text, which can be formatted with reStructuredText markup, and the file for your logo.

**Comment by jpgill86** [comment]
Wonderful, thanks @apdavison! Here are some details that should help you.

Logo in several sizes: https://github.com/jpgill86/neurotic/tree/master/neurotic/gui/icons/img

License: MIT (https://github.com/jpgill86/neurotic/blob/master/LICENSE)

Links:

- Documentation: https://neurotic.readthedocs.io/
- Download: https://pypi.org/project/neurotic/
- Source Code: https://github.com/jpgill86/neurotic
- Issue Tracker: https://github.com/jpgill86/neurotic/issues

Description in reStructuredText:

```
**neurotic** is an interactive data visualization app that allows
neuroscientists to synchronize raw electrophysiology data with video of the
experiment. Without doing any programming, users can review and annotate their
experimental data stored in a Neo_-compatible format (see `Neo's docs`_ for
file types) and see video of the behavior or stimuli that accompanied the
signals.

Before plotting data, **neurotic** can perform basic data processing, such as
signal filtering and spike detection. It can also fetch data files from
internet-accessible servers, which is convenient for collaborations or for
working from multiple computers.

**neurotic** is built in Python and can run as a standalone app for Windows,
macOS, or Linux. It also provides an API that can be used as part of a data
analysis workflow with Jupyter notebooks or Python scripts. The app launches
with a complete working example, and a working `example Jupyter notebook`_ is
provided too.

**neurotic**'s graphical user interface is powered by the ephyviewer_ library.

.. _ephyviewer: https://github.com/NeuralEnsemble/ephyviewer
.. _example Jupyter notebook: https://github.com/jpgill86/neurotic/blob/master/neurotic/example/example-notebook.ipynb
.. _Neo:        https://neuralensemble.org/neo/
.. _Neo's docs: https://neo.readthedocs.io/en/latest/io.html#module-neo.io
```

**Comment by jpgill86** [comment]
Hi @apdavison, is there anything else you need from me for this?

**Comment by apdavison** [comment]
@jpgill86 no, I don't think so. I'll let you know once I've updated the site.

**Comment by jpgill86** [comment]
ping @apdavison 😉

**Comment by apdavison** [comment]
https://neuralensemble.org/neurotic/

**Comment by jpgill86** [comment]
Thank you @apdavison, it looks great!

**Comment by jpgill86** [comment]
Hello again @apdavison... the URL you shared works great, but I noticed that neurotic has not been added to the drop-down menu listing all of the available software, which makes it difficult to find the page.

![image](https://user-images.githubusercontent.com/241234/75269557-1b848700-57c7-11ea-9033-65809476ae0b.png)

Could you add it for me?

**Comment by jpgill86** [comment]
Hello again @apdavison,

I noticed that, in addition to the issues I described in the posts above from February 25, the neurotic logo is now a broken image:

![image](https://user-images.githubusercontent.com/241234/80288162-19c23b80-8704-11ea-941b-b5c44721e1b0.png)

Is it possible to fix this (and, time permitting, the other issue described above)?

Jeff

**Comment by apdavison** [comment]
This should now be fixed and stay fixed!

**Comment by jpgill86** [comment]
Yes, it all appears to be working. Thanks @apdavison!
