### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by jpgill86** [jpgill86/neurotic#24]
Hey @samuelgarcia! I wanted to let you know that I just released the code I use to interact with ephyviewer as a Python package! I think you might like it, and I would love to get your feedback.

The objective is to bring ephyviewer to the non-programmers, like my labmates, haha. Take a look at the README for details:

https://github.com/jpgill86/neurotic

It's still very simple and is far from perfect, but I have been using it for daily activities for a long time and find it incredibly useful. I still have many plans for improvements.

It currently depends on the "experimental" branch of my fork of ephyviewer (which currently just has one change from a pull request that hasn't been merged yet). So, to install it on your system I would recommend creating a new Python environment and following the README's instructions. I hope it works for you! 🤞

**Comment by samuelgarcia** [comment]
Hi @jpgill86.
This look super great.
I installed it but have a small bug in my installation (tqdm, PyQt5) so I can't test it straight now.
I will give some feedback soon (more or less 2 weeks! ) :)

If you want, you can promote it in the doc of ephyviewer in the index page as example what can be done. I think you could also ask   Andrew  Davison to integrate it into neuralensemble.org pages.

**Comment by jpgill86** [comment]
Thanks for the feedback in #30!
