### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by samuelgarcia** [jpgill86/neurotic#30]
I guess this is an installation problem with pyqt5 or something like this.
I will have a look later.
I oen an issue and when fixed I will writte some notes here.

```
Ready
debug False
Traceback (most recent call last):
  File "/home/samuel/Documents/projet/neurotic/neurotic/gui/standalone.py", line 286, in launch
    win = ephyviewer_config.create_ephyviewer_window(theme=self.theme, support_increased_line_width=self.support_increased_line_width)
  File "/home/samuel/Documents/projet/neurotic/neurotic/gui/config.py", line 329, in create_ephyviewer_window
    raise ValueError('This file type cannot be read with fast loading (lazy=True): {}'.format(abs_path(self.metadata, 'data_file')))
ValueError: This file type cannot be read with fast loading (lazy=True): /home/samuel/Documents/projet/neurotic/neurotic/example/example-data/data.axgx
[samuel-HP-Z800-Workstation:13609] *** Process received signal ***
[samuel-HP-Z800-Workstation:13609] Signal: Abandon (6)
```

**Comment by jpgill86** [comment]
That sounds like something different than an installation error.

The example is built around an AxoGraph file (``data.axgx``). The message ``This file type cannot be read with fast loading (lazy=True)`` is saying you don't have a version of Neo installed with AxographRawIO, a new RawIO I recently implemented and that was merged into Neo master about a month ago (NeuralEnsemble/python-neo#670). It should be included in the next release of Neo.

The first thing you could try I turning off "Fast loading" in the options menu. This can also be done using the ``--no-lazy`` flag on the command line. As long as you have Neo >= 0.7.0, you should have the non-raw version of AxographIO released last year.

The other thing you can do is install the development version of Neo which has the RawIO. My requirements files are setup to do this for you. Equivalently, you can run

``pip install git+https://github.com/NeuralEnsemble/python-neo.git``

Let me know if that works for you!

**Comment by jpgill86** [comment]
Also, I can see you must have an old version of ephyviewer installed because the debug statement was printed. My app depends on having a very recent version of ephyviewer as well, one that is so new you have to use a branch on my fork!

``pip install git+https://github.com/jpgill86/ephyviewer.git@experimental``

**Comment by samuelgarcia** [comment]
Oups. That is true.
Both neo an dephyviewer was outdated on the machine I tested.
Sorry.
But finally it was an installation problem :)

I will try it tomorow.

thank, sorry for the noise.

**Comment by jpgill86** [comment]
Haha, I guess you were right about that!

**Comment by samuelgarcia** [comment]
WIth proper ```git pull upstream master``` in all my codes.
It now works.
I just had a very brief tour.
Congratulation.
This look great.
The idea of integrating data fetching is really super cool!!

With you won't be rich because it is open source for labs, but you will amazingly famous.

**Comment by jpgill86** [comment]
Hahaha, I'm glad you like it!

The data fetching even works with data on servers requiring authentication, such as a private repo on GIN. If a researcher can convince their collaborators to install the app (still not as easy as it should be), they can make their data available on GIN or elsewhere, private or public, and then share their metadata.yml file to disseminate their data. 😁

Do you think the NeuralEnsemble mailing list would be a good place to announce the project?

**Comment by samuelgarcia** [comment]
Yes you can use the list. It is a good idea.


To make install easier, we can release very soon ephyviewer if you want.
neo relase is bit slow because it is hard to coordinate ourself.
But for a new IO normally we can relase quickly.
Open an issue in neo for asking release otehrwise you could wait for long

**Comment by jpgill86** [comment]
I like these ideas and will do that!
